---
title: "Enabling Experiential Learning: Utah State University's Analytics Solutions Center"
format: gfm
---

Higher education is changing. Public trust in the value proposition of universities and colleges has eroded in recent decades while their traditional institutional function of storing, creating, and disseminating knowledge has been challenged by content delivery on the internet and private industry investment in research and development. In response, there has been a growing emphasis within higher education on what university and colleges can uniquely provide students, including experiential learning. However, there is a dearth of research on how to enable experiential learning effectively. We detail how the Analytics Solutions Center at Utah State University has incentivized alignment of its faculty and industry partners to enable transformative experiential learning experiences for students.

## Project Organization

- `/code` Scripts with prefixes (e.g., `01_import-data.py`, `02_clean-data.py`) and functions in `/code/src`.
- `/data` Simulated and real data, the latter not pushed.
- `/figures` PNG images and plots.
- `/output` Output from model runs, not pushed.
- `/presentations` Presentation slides.
- `/private` A catch-all folder for miscellaneous files, not pushed.
- `/writing` Paper, report, and case studies.
- `/.quarto` Hidden Quarto project library, not pushed.
- `/.venv` Hidden Python project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version file.
- `LICENSE` MIT License for "as is" permission.
- `README.md` GitHub-flavored markdown README rendered from `README.qmd`.
- `README.qmd` Quarto markdown README to edit and render into `README.md`.
- `_quarto.yml` Quarto project configuration file.
- `pyproject.toml` Python project environment configuration file.
- `uv.lock` Python project environment lockfile.

## Project Environment

After cloning this repository, go to the project's terminal in Positron and run `uv run` to create the `/.venv` project library and install the specified Python and library versions.

For more details on using Python, Positron, GitHub, Quarto, etc. see the recommended [data stack](https://github.com/marcdotson/data-stack).
